matrix:
  include:
    - language: python
      python: 3.6
      sudo: required
      install: pip install -r server/requirements.txt
      services:
        - docker
      before_script:
        - docker pull mongo
        - docker run -dp 27017:27017 mongo:3.4.4
        - cd server
        - cp sample-config.yaml config.yaml
      script:
        - pytest -vv --cov=./
      after_script:
        - codecov

    - language: node_js
      node_js:
        - "node"
      install:
        - npm install -g istanbul
      before_script:
        - cd server
        - npm install
      script:
        - ./node_modules/eslint/bin/eslint.js .
        - istanbul cover --hook-run-in-context --dir public/js/coverage ./node_modules/mocha/bin/_mocha -- js/test
      after_script:
        - codecov

    - language: android
      jdk: oraclejdk8
      env:
        global:
          - ANDROID_API_LEVEL=25
          - BUILD_TOOLS_VERSION=25.0.2
      android:
        update_sdk: true
        components:
          - tools
          - android-$ANDROID_API_LEVEL
          - build-tools-$BUILD_TOOLS_VERSION
          - extra-android-m2repository
      before_script:
        - cd mobile/android/WirelessDebugger
      script:
        - ./gradlew build test
      after_success:
        — bash <(curl -s https://codecov.io/bash)

    - language: swift
      osx_image: xcode8.3
      before_script:
        - cd mobile/ios/WirelessDebug
      script:
        - xcodebuild -scheme Test -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3.1' build test
      after_success:
        - bash <(curl -s https://codecov.io/bash)
