matrix:
  include:
    - language: python
      python: 3.6
      sudo: required
      install: pip install -r server/requirements.txt
      services:
        - docker
      before_script:
        - docker pull mongo
        - docker run -dp 27017:27017 mongo:3.4.4
        - cd server
        - cp sample-config.yaml config.yaml
      script:
        - pytest -vv --cov=./
      after_script:
        - codecov

    - language: node_js
      node_js:
        - "node"
      install:
        - npm install -g istanbul
      before_script:
        - cd server
        - npm install
      script:
        - istanbul cover --hook-run-in-context --dir public/js/coverage ./node_modules/mocha/bin/_mocha -- js/test
      after_script:
        - codecov

    - language: swift
      osx_image: xcode8.3
      before_script:
        - cd mobile/ios/WirelessDebug
      script:
        - xcodebuild -scheme Test -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3.1' build test
      after_success:
        - bash <(curl -s https://codecov.io/bash)

notifications:
  slack:
    secure: IQiN2AhZfF2YIKKFR/+OOzKCJcle447VJJuf4rBKlacqv3RotzTx0zKxGl6w6e9opGeSbAGrmUOtR8isGSPe8hYfWxV4QVeetQvsGGygIavMe7JOn0bridwsbTIa1XbiMv/jYaL2fl8QGLGkVHkP8VgQmj4KaqSftN2P2gJ6QCgF3zDQEz2Yp3/a5Eni2n3Vfh2NzO5O3I3DrSFT7ohwIe+x9m+El8qP1Qqa+KB9MPkVcQxejzOzdcG2mIuWT9mrm5QDbs+SRtpUGbDZgiNdMzm7cwSsFHHI7TCjN3agSnSNWb6zbJChj5dqRRNXMLP5qnMr78jJ01p7vM+i2QVQoSf7sobe9XULFVkaRMDkdTXG3h6kOlflkInjE7RcHRyvJ/ELFE+FGPMgZaV4IO+OGbM4Z0FcRZ2KqNZUTc1vsvImJvfJ7oynDvRRqo04j4+W4XonHBKiQCL1TNa6MR2MsExSnBzhlk7nSePjb/CrU1btHluKvKwGgRhzmeZ/64sCkfFFq1rUcSnM8ymbL3R0q4XYdIyhzM6gV5BBvAUEBJDk0YUrK5U999VYHuRydVHWficRHq8ZFMCly4Z37a4K5ncxA6rIV+BtlTLQi8Zhuq/l/sG7oHhMFDNaqQWfKRttdJ/y40YCFOfZUX+wTH1IkRKJyxuabxULmBq5zCSWOlE=
