runtime: python
env: flex
entrypoint: python widb_server.py

runtime_config:
  python_version: 3

health_check:
  enable_health_check: False

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
