runtime: python
env: flex
api_version: 1
threadsafe: true

db: mongodb://localhost:27017

runtime_config:
        python_version: 3

# [START handlers]
handlers:
- url: /.*
  script: widb_server.app
# [END handlers]

# [START libraries]
# [END libraries]
