runtime: python
env: flex
api_version: 1
threadsafe: true

runtime_config:
        python_versoin: 3

# [START handlers]
handlers: 
- url: /.*
  script: widb_server.app
# [END handlers]

# [START libraries]
# [END libraries]
