runtime: python
env: flex
entrypoint: python widb_server.py 

#db: mongodb://localhost:27017

runtime_config:
        python_version: 3

# [START handlers]
# [END handlers]

# [START libraries]
# [END libraries]
