title: Wireless Debugger
name: Wireless Debugger
baseurl: "https://sumnerevans.github.io/wireless-debugging"
description: >
  Wireless Debugger is a mobile SDK and sample web server for streaming and
  parsing mobile app logs and displaying them in a web UI console.
theme: jekyll-theme-architect
